SHOW DATABASES;

USE StoreFont;

SHOW TABLES;

CREATE FUNCTION Cal_Orders(MONTH INT ,YEAR INT)
RETURNS INT( SELECT COUNT(OrderId) FROM Orders GROUP BY MONTH(OrderDate));

CREATE FUNCTION Max_Order(YEAR INT)
RETURNS INT(SELECT MAX(MONTH(YEAR(OrderDate))) GROUP BY OrderId);

